# Generated by Django 5.1.4 on 2025-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('sticker_path', models.CharField(max_length=100)),
            ],
        ),
    ]
