# Generated by Django 5.1.4 on 2025-01-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_api', '0002_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='num',
        ),
        migrations.AddField(
            model_name='diary',
            name='id',
            field=models.BigAutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
